adjective1 = input('Enter the place you went  ')
noun1 = input('Describe what you saw  ')
adjective2 = input('Enter the adjective  ')
verb1 = input('Enter the verb  ')
adjective3 = input('And another adjective  ')
print(f'Today I went to a  {adjective1} zoo. ')
print(f'In an exhibit I saw a {noun1}. ')
print(f'{noun1} was {adjective2} and {verb1}. ')
print(f'I was {adjective3}.')